services:
  app:
    image: febrile42/cyberpunk-roller:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DB_PATH: /var/lib/cyberpunk-roller/fire.db
    volumes:
      - db_data:/var/lib/cyberpunk-roller

volumes:
  db_data:
